"""empty message

Revision ID: 9e477fb2233b
Revises: 
Create Date: 2022-05-23 15:59:39.688901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e477fb2233b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phylum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=140), nullable=False),
    sa.Column('codename', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category')
    )
    op.create_index(op.f('ix_phylum_codename'), 'phylum', ['codename'], unique=True)
    op.create_table('subgroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(length=140), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subgroup_division'), 'subgroup', ['division'], unique=True)
    op.create_table('monster',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('generation', sa.Integer(), nullable=False),
    sa.Column('phylum', sa.String(length=100), nullable=False),
    sa.Column('variation', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['phylum'], ['phylum.codename'], ),
    sa.ForeignKeyConstraint(['variation'], ['subgroup.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monster_generation'), 'monster', ['generation'], unique=False)
    op.create_index(op.f('ix_monster_name'), 'monster', ['name'], unique=True)
    op.create_table('ailments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mon_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=250), nullable=True),
    sa.Column('blight', sa.String(length=140), nullable=True),
    sa.Column('natural', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['mon_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mon_id', sa.Integer(), nullable=False),
    sa.Column('MHF', sa.Boolean(), nullable=True),
    sa.Column('MHF2', sa.Boolean(), nullable=True),
    sa.Column('MH3rd', sa.Boolean(), nullable=True),
    sa.Column('MH3U', sa.Boolean(), nullable=True),
    sa.Column('MH4U', sa.Boolean(), nullable=True),
    sa.Column('MHGU', sa.Boolean(), nullable=True),
    sa.Column('MHWI', sa.Boolean(), nullable=True),
    sa.Column('MHRS', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mon_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('item_weak',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mon_id', sa.Integer(), nullable=False),
    sa.Column('shock_trap', sa.Boolean(), nullable=True),
    sa.Column('pitfall_trap', sa.Boolean(), nullable=True),
    sa.Column('flash_bomb', sa.Boolean(), nullable=True),
    sa.Column('sonic_bomb', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mon_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proficiency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mon_id', sa.Integer(), nullable=False),
    sa.Column('fire', sa.Boolean(), nullable=True),
    sa.Column('water', sa.Boolean(), nullable=True),
    sa.Column('thunder', sa.Boolean(), nullable=True),
    sa.Column('ice', sa.Boolean(), nullable=True),
    sa.Column('dragon', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mon_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('related',
    sa.Column('main_id', sa.Integer(), nullable=True),
    sa.Column('subspecies_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['main_id'], ['monster.id'], ),
    sa.ForeignKeyConstraint(['subspecies_id'], ['monster.id'], )
    )
    op.create_table('weakness',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mon_id', sa.Integer(), nullable=False),
    sa.Column('fire', sa.Boolean(), nullable=True),
    sa.Column('water', sa.Boolean(), nullable=True),
    sa.Column('thunder', sa.Boolean(), nullable=True),
    sa.Column('ice', sa.Boolean(), nullable=True),
    sa.Column('dragon', sa.Boolean(), nullable=True),
    sa.Column('poison', sa.Boolean(), nullable=True),
    sa.Column('sleep', sa.Boolean(), nullable=True),
    sa.Column('para', sa.Boolean(), nullable=True),
    sa.Column('blast', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['mon_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weakpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cut', sa.String(length=140), nullable=True),
    sa.Column('impact', sa.String(length=140), nullable=True),
    sa.Column('projectile', sa.String(length=140), nullable=True),
    sa.Column('mon_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['mon_id'], ['monster.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('weakpoints')
    op.drop_table('weakness')
    op.drop_table('related')
    op.drop_table('proficiency')
    op.drop_table('item_weak')
    op.drop_table('games')
    op.drop_table('ailments')
    op.drop_index(op.f('ix_monster_name'), table_name='monster')
    op.drop_index(op.f('ix_monster_generation'), table_name='monster')
    op.drop_table('monster')
    op.drop_index(op.f('ix_subgroup_division'), table_name='subgroup')
    op.drop_table('subgroup')
    op.drop_index(op.f('ix_phylum_codename'), table_name='phylum')
    op.drop_table('phylum')
    # ### end Alembic commands ###
